FROM node:18 AS build 

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build 

FROM nginx:alpine 

# RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /app/build /usr/share/nginx/html

# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
