version: "3"

services:

  database:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - ./mydata:/var/lib/mysql
    networks:
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    ports:
      - 8090:80
    networks:
      - database
    environment:
      PMA_HOST: database
      PMA_USER: test
      PMA_PASSWORD: test

  api:

    build:
      context: ./app
      dockerfile: Dockerfile
    ports :
      - "3000:3000"  
    container_name : api
    restart: always
    networks: 
      - database 
    environment:
      DB_HOST: database
      DB_USER: 'test'
      DB_PASSWORD: 'test'
      DB_NAME: 'mydatabase'
 
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports :
      - "80:80"
    container_name : frontend
    restart: always
    networks: 
      - database       

networks:
  database:

